[package]
name = "pnova"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jf-plonk = { git = "https://github.com/EspressoSystems/jellyfish", package = "jf-plonk" }
