[package]
name = "pnova"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ec = "0.4.0"
ark-poly = "0.4.0"
jf_plonk = { git = "https://github.com/EspressoSystems/jellyfish", package = "jf-plonk" }
jf_primitives = { git = "https://github.com/EspressoSystems/jellyfish", package = "jf-primitives"}
jf_utils = { git = "https://github.com/EspressoSystems/jellyfish", package = "jf-utils"}
